#SPDX-License-Identifier: MIT-0
---
# tasks file for wordpress
- name: Instalar WordPress
  hosts: webserver
  become: yes
  tasks:
    - name: Instalar dependencias de WordPress
      ansible.builtin.package:
        name:
          - php
          - php-mysql
          - php-xml
          - php-gd
          - php-curl
        state: present

    - name: Descargar WordPress
      ansible.builtin.get_url:
        url: https://wordpress.org/latest.tar.gz
        dest: /tmp/wordpress.tar.gz

    - name: Descomprimir WordPress
      ansible.builtin.unarchive:
        src: /tmp/wordpress.tar.gz
        dest: /var/www/html/
        remote_src: yes

    - name: Configurar permisos de WordPress
      ansible.builtin.file:
    
    - name: Instalar gnix
      ansible.builtin.package:
        name: nginx
        state: present

    - name: Activar servicio de Nginx
      ansible.builtin.systemd:
        name: nginx
        state: started
        enabled: yes

    - name: Configurar Nginx para WordPress
      ansible.builtin.template:
        src: wordpress/templates/nginx_wordpress.conf.j2
        dest: /etc/nginx/sites-available/wordpress.conf
        mode: '0644'
      notify:
        - Reiniciar Nginx 